### ISSUE TITLE
Cannot connect to runtime

### ISSUE THREAD

**Issue by amilajack** [bpasero/debug-electron-vscode#1]
I'm getting the following issue. Thoughts on what could be causing this?

<img width="565" alt="screen shot 2018-03-10 at 8 41 35 pm" src="https://user-images.githubusercontent.com/6374832/37249816-a36a241c-24a3-11e8-85da-6f5ed1e71076.png">

**Comment by DeekshithShetty** [comment]
Did you try using "protocol": "inspector"?

**Comment by amilajack** [comment]
Its been a while. I think I may have gotten this working. Will close and reopen if i run into any issues
